/**
 * FSMS V2 — generated database types.
 *
 * AUTO-GENERATED by scripts/gen_db_types.mjs — DO NOT EDIT BY HAND.
 * Regenerate after any schema change:
 *   LOCAL_DB_URL=postgres://fsms:fsms_dev@127.0.0.1:5432/fsms_v2 node scripts/gen_db_types.mjs
 *
 * Equivalent to `supabase gen types typescript --db-url …`. Schema drift
 * breaks the TypeScript build (typed clients), which is intentional.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Enums = {
  app_locale: "en" | "ru" | "fr" | "zh";
  assessment_status: "draft" | "published" | "archived";
  attendance_status: "present" | "absent" | "late";
  class_status: "active" | "archived" | "ended";
  curriculum_item_kind: "skill" | "grammar" | "vocabulary" | "expression";
  curriculum_status: "draft" | "review" | "published" | "archived";
  evidence_quality: "weak" | "ok" | "strong";
  evidence_source: "assessment" | "practice" | "learning-check" | "lesson-skill" | "manual";
  gender: "male" | "female" | "other";
  grant_status: "requested" | "granted" | "expired" | "revoked";
  homework_status: "assigned" | "submitted" | "graded" | "overdue" | "missing";
  learner_type: "children" | "teenagers" | "adults" | "general";
  lesson_status: "scheduled" | "completed" | "cancelled";
  mapping_status: "proposed" | "verified" | "rejected";
  material_type: "textbook" | "workbook" | "reader" | "media" | "other";
  payment_status: "pending" | "confirmed" | "void";
  progress_status: "not-evaluated" | "not-yet" | "almost" | "achieved" | "mastered";
  rating_value: "1" | "2" | "3" | "4" | "5";
  role_base: "admin1" | "admin" | "manager" | "accountant" | "secretary" | "teacher" | "parent" | "student";
  salary_status: "pending" | "paid";
  spotlight_status: "draft" | "published" | "locked";
  user_status: "active" | "pending" | "deactivated" | "refused";
};

export type Database = {
  public: {
    Tables: {
      academic_years: {
        Row: {
      id: string;
      school_id: string;
      name: string;
      starts_on: string | null;
      ends_on: string | null;
      current: boolean;
        };
        Insert: {
      id?: string;
      school_id: string;
      name: string;
      starts_on?: string | null;
      ends_on?: string | null;
      current?: boolean;
        };
        Update: {
      id?: string;
      school_id?: string;
      name?: string;
      starts_on?: string | null;
      ends_on?: string | null;
      current?: boolean;
        };
        Relationships: [];
      };
      achievement_opportunities: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string | null;
      badge_id: string | null;
      kind: string | null;
      payload: Json;
      status: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id?: string | null;
      badge_id?: string | null;
      kind?: string | null;
      payload?: Json;
      status?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string | null;
      badge_id?: string | null;
      kind?: string | null;
      payload?: Json;
      status?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      achievement_opportunity_states: {
        Row: {
      id: string;
      school_id: string;
      opportunity_id: string;
      state: string | null;
      decided_by: string | null;
      decided_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      opportunity_id: string;
      state?: string | null;
      decided_by?: string | null;
      decided_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      opportunity_id?: string;
      state?: string | null;
      decided_by?: string | null;
      decided_at?: string;
        };
        Relationships: [];
      };
      activities: {
        Row: {
      id: string;
      school_id: string;
      type: string;
      text: Json;
      actor_id: string | null;
      ref_id: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      type: string;
      text?: Json;
      actor_id?: string | null;
      ref_id?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      type?: string;
      text?: Json;
      actor_id?: string | null;
      ref_id?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      assessment_tests: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string | null;
      class_id: string | null;
      title: string | null;
      source_month: string | null;
      from_date: string | null;
      to_date: string | null;
      difficulty: string | null;
      types: Json;
      task_count: number | null;
      tasks: Json | null;
      status: Enums["assessment_status"];
      mode: string | null;
      created_by: string | null;
      created_at: string;
      published_at: string | null;
      updated_at: string;
      archived_at: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id?: string | null;
      class_id?: string | null;
      title?: string | null;
      source_month?: string | null;
      from_date?: string | null;
      to_date?: string | null;
      difficulty?: string | null;
      types?: Json;
      task_count?: number | null;
      tasks?: Json | null;
      status?: Enums["assessment_status"];
      mode?: string | null;
      created_by?: string | null;
      created_at?: string;
      published_at?: string | null;
      updated_at?: string;
      archived_at?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string | null;
      class_id?: string | null;
      title?: string | null;
      source_month?: string | null;
      from_date?: string | null;
      to_date?: string | null;
      difficulty?: string | null;
      types?: Json;
      task_count?: number | null;
      tasks?: Json | null;
      status?: Enums["assessment_status"];
      mode?: string | null;
      created_by?: string | null;
      created_at?: string;
      published_at?: string | null;
      updated_at?: string;
      archived_at?: string | null;
        };
        Relationships: [];
      };
      assessments: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      date: string;
      class_id: string | null;
      student_id: string;
      type: string | null;
      title: string | null;
      score: number | null;
      max_score: number | null;
      note: string | null;
      recorded_by: string | null;
      edited_by: string | null;
      edited_at: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      date: string;
      class_id?: string | null;
      student_id: string;
      type?: string | null;
      title?: string | null;
      score?: number | null;
      max_score?: number | null;
      note?: string | null;
      recorded_by?: string | null;
      edited_by?: string | null;
      edited_at?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      date?: string;
      class_id?: string | null;
      student_id?: string;
      type?: string | null;
      title?: string | null;
      score?: number | null;
      max_score?: number | null;
      note?: string | null;
      recorded_by?: string | null;
      edited_by?: string | null;
      edited_at?: string | null;
        };
        Relationships: [];
      };
      attendance: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      date: string;
      class_id: string;
      student_id: string;
      status: Enums["attendance_status"];
      minutes_late: number;
      note: string | null;
      taken_by: string | null;
      taken_at: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      date: string;
      class_id: string;
      student_id: string;
      status: Enums["attendance_status"];
      minutes_late?: number;
      note?: string | null;
      taken_by?: string | null;
      taken_at?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      date?: string;
      class_id?: string;
      student_id?: string;
      status?: Enums["attendance_status"];
      minutes_late?: number;
      note?: string | null;
      taken_by?: string | null;
      taken_at?: string | null;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
      id: string;
      school_id: string;
      actor_id: string | null;
      action: string;
      entity: string;
      entity_id: string | null;
      before: Json | null;
      after: Json | null;
      ip: string | null;
      at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      actor_id?: string | null;
      action: string;
      entity: string;
      entity_id?: string | null;
      before?: Json | null;
      after?: Json | null;
      ip?: string | null;
      at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      actor_id?: string | null;
      action?: string;
      entity?: string;
      entity_id?: string | null;
      before?: Json | null;
      after?: Json | null;
      ip?: string | null;
      at?: string;
        };
        Relationships: [];
      };
      badge_approvals: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string | null;
      badge_id: string | null;
      requested_by: string | null;
      status: string | null;
      decided_by: string | null;
      decided_at: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id?: string | null;
      badge_id?: string | null;
      requested_by?: string | null;
      status?: string | null;
      decided_by?: string | null;
      decided_at?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string | null;
      badge_id?: string | null;
      requested_by?: string | null;
      status?: string | null;
      decided_by?: string | null;
      decided_at?: string | null;
        };
        Relationships: [];
      };
      badge_objectives: {
        Row: {
      id: string;
      school_id: string;
      badge_id: string;
      objective_id: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      badge_id: string;
      objective_id: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      badge_id?: string;
      objective_id?: string;
        };
        Relationships: [];
      };
      badge_targets: {
        Row: {
      id: string;
      school_id: string;
      badge_id: string;
      target_id: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      badge_id: string;
      target_id: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      badge_id?: string;
      target_id?: string;
        };
        Relationships: [];
      };
      badges: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      code: string | null;
      name: Json;
      level_code: string | null;
      image_url: string | null;
      description: Json;
      active: boolean;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      code?: string | null;
      name?: Json;
      level_code?: string | null;
      image_url?: string | null;
      description?: Json;
      active?: boolean;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      code?: string | null;
      name?: Json;
      level_code?: string | null;
      image_url?: string | null;
      description?: Json;
      active?: boolean;
      created_at?: string;
        };
        Relationships: [];
      };
      certificates: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string | null;
      serial: string | null;
      cert: Json;
      issued_by: string | null;
      issued_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id?: string | null;
      serial?: string | null;
      cert?: Json;
      issued_by?: string | null;
      issued_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string | null;
      serial?: string | null;
      cert?: Json;
      issued_by?: string | null;
      issued_at?: string;
        };
        Relationships: [];
      };
      class_day_times: {
        Row: {
      class_id: string;
      day_of_week: number;
      start_time: string;
      end_time: string;
        };
        Insert: {
      class_id: string;
      day_of_week: number;
      start_time: string;
      end_time: string;
        };
        Update: {
      class_id?: string;
      day_of_week?: number;
      start_time?: string;
      end_time?: string;
        };
        Relationships: [];
      };
      class_teachers: {
        Row: {
      class_id: string;
      user_id: string;
      is_primary: boolean;
      assigned_by: string | null;
      assigned_at: string;
        };
        Insert: {
      class_id: string;
      user_id: string;
      is_primary?: boolean;
      assigned_by?: string | null;
      assigned_at?: string;
        };
        Update: {
      class_id?: string;
      user_id?: string;
      is_primary?: boolean;
      assigned_by?: string | null;
      assigned_at?: string;
        };
        Relationships: [];
      };
      classes: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      name: string;
      level_code: string | null;
      academic_year_id: string | null;
      term_id: string | null;
      room: string | null;
      schedule: string | null;
      start_time: string | null;
      end_time: string | null;
      days: string | null;
      status: Enums["class_status"];
      class_type: string | null;
      learner_type: Enums["learner_type"] | null;
      link: string | null;
      link_password: string | null;
      link2: string | null;
      link2_password: string | null;
      recurrence: string | null;
      specific_dates: Json;
      fee: number | null;
      fee_currency: string | null;
      special_course_id: string | null;
      primary_material_id: string | null;
      created_by: string | null;
      created_at: string;
      updated_at: string;
      deleted_at: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      name: string;
      level_code?: string | null;
      academic_year_id?: string | null;
      term_id?: string | null;
      room?: string | null;
      schedule?: string | null;
      start_time?: string | null;
      end_time?: string | null;
      days?: string | null;
      status?: Enums["class_status"];
      class_type?: string | null;
      learner_type?: Enums["learner_type"] | null;
      link?: string | null;
      link_password?: string | null;
      link2?: string | null;
      link2_password?: string | null;
      recurrence?: string | null;
      specific_dates?: Json;
      fee?: number | null;
      fee_currency?: string | null;
      special_course_id?: string | null;
      primary_material_id?: string | null;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
      deleted_at?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      name?: string;
      level_code?: string | null;
      academic_year_id?: string | null;
      term_id?: string | null;
      room?: string | null;
      schedule?: string | null;
      start_time?: string | null;
      end_time?: string | null;
      days?: string | null;
      status?: Enums["class_status"];
      class_type?: string | null;
      learner_type?: Enums["learner_type"] | null;
      link?: string | null;
      link_password?: string | null;
      link2?: string | null;
      link2_password?: string | null;
      recurrence?: string | null;
      specific_dates?: Json;
      fee?: number | null;
      fee_currency?: string | null;
      special_course_id?: string | null;
      primary_material_id?: string | null;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
      deleted_at?: string | null;
        };
        Relationships: [];
      };
      content_migrations: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      source: string | null;
      target: string | null;
      status: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      source?: string | null;
      target?: string | null;
      status?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      source?: string | null;
      target?: string | null;
      status?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      content_translations: {
        Row: {
      id: string;
      school_id: string;
      content_hash: string;
      locale: Enums["app_locale"];
      fields: Json;
      created_at: string;
      updated_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      content_hash: string;
      locale: Enums["app_locale"];
      fields?: Json;
      created_at?: string;
      updated_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      content_hash?: string;
      locale?: Enums["app_locale"];
      fields?: Json;
      created_at?: string;
      updated_at?: string;
        };
        Relationships: [];
      };
      curricula: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      programme_id: string | null;
      title: Json;
      publisher: string | null;
      status: Enums["curriculum_status"];
      source_hash: string | null;
      imported_at: string | null;
      archived_at: string | null;
      deleted_at: string | null;
      created_at: string;
      updated_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      programme_id?: string | null;
      title?: Json;
      publisher?: string | null;
      status?: Enums["curriculum_status"];
      source_hash?: string | null;
      imported_at?: string | null;
      archived_at?: string | null;
      deleted_at?: string | null;
      created_at?: string;
      updated_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      programme_id?: string | null;
      title?: Json;
      publisher?: string | null;
      status?: Enums["curriculum_status"];
      source_hash?: string | null;
      imported_at?: string | null;
      archived_at?: string | null;
      deleted_at?: string | null;
      created_at?: string;
      updated_at?: string;
        };
        Relationships: [];
      };
      curriculum_access: {
        Row: {
      id: string;
      school_id: string;
      curriculum_id: string;
      scope_type: string | null;
      scope_id: string | null;
      access_mode: string | null;
      updated_by: string | null;
      updated_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      curriculum_id: string;
      scope_type?: string | null;
      scope_id?: string | null;
      access_mode?: string | null;
      updated_by?: string | null;
      updated_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      curriculum_id?: string;
      scope_type?: string | null;
      scope_id?: string | null;
      access_mode?: string | null;
      updated_by?: string | null;
      updated_at?: string;
        };
        Relationships: [];
      };
      curriculum_assignments: {
        Row: {
      id: string;
      school_id: string;
      curriculum_id: string;
      class_id: string;
      assigned_by: string | null;
      assigned_at: string;
      is_primary: boolean;
        };
        Insert: {
      id?: string;
      school_id: string;
      curriculum_id: string;
      class_id: string;
      assigned_by?: string | null;
      assigned_at?: string;
      is_primary?: boolean;
        };
        Update: {
      id?: string;
      school_id?: string;
      curriculum_id?: string;
      class_id?: string;
      assigned_by?: string | null;
      assigned_at?: string;
      is_primary?: boolean;
        };
        Relationships: [];
      };
      curriculum_imports: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      curriculum_id: string | null;
      source_text: string | null;
      parsed: Json | null;
      status: string | null;
      created_by: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      curriculum_id?: string | null;
      source_text?: string | null;
      parsed?: Json | null;
      status?: string | null;
      created_by?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      curriculum_id?: string | null;
      source_text?: string | null;
      parsed?: Json | null;
      status?: string | null;
      created_by?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      curriculum_lesson_items: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      curriculum_lesson_id: string;
      kind: Enums["curriculum_item_kind"];
      label: string | null;
      value: Json;
      no: number | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      curriculum_lesson_id: string;
      kind: Enums["curriculum_item_kind"];
      label?: string | null;
      value?: Json;
      no?: number | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      curriculum_lesson_id?: string;
      kind?: Enums["curriculum_item_kind"];
      label?: string | null;
      value?: Json;
      no?: number | null;
        };
        Relationships: [];
      };
      curriculum_lesson_progress: {
        Row: {
      id: string;
      school_id: string;
      student_id: string;
      lesson_id: string;
      status: string | null;
      updated_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      student_id: string;
      lesson_id: string;
      status?: string | null;
      updated_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      student_id?: string;
      lesson_id?: string;
      status?: string | null;
      updated_at?: string;
        };
        Relationships: [];
      };
      curriculum_lessons: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      curriculum_id: string;
      week_id: string | null;
      title: Json;
      no: number | null;
      lesson_ref: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      curriculum_id: string;
      week_id?: string | null;
      title?: Json;
      no?: number | null;
      lesson_ref?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      curriculum_id?: string;
      week_id?: string | null;
      title?: Json;
      no?: number | null;
      lesson_ref?: string | null;
        };
        Relationships: [];
      };
      curriculum_phases: {
        Row: {
      id: string;
      school_id: string;
      curriculum_id: string;
      title: Json;
      no: number | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      curriculum_id: string;
      title?: Json;
      no?: number | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      curriculum_id?: string;
      title?: Json;
      no?: number | null;
        };
        Relationships: [];
      };
      curriculum_reviews: {
        Row: {
      id: string;
      school_id: string;
      curriculum_id: string;
      reviewer: string | null;
      status: string | null;
      note: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      curriculum_id: string;
      reviewer?: string | null;
      status?: string | null;
      note?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      curriculum_id?: string;
      reviewer?: string | null;
      status?: string | null;
      note?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      curriculum_topics: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      title: Json;
      level_code: string | null;
      course_section: string | null;
      published: boolean;
      published_by: string | null;
      published_at: string | null;
      archived: boolean;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      title?: Json;
      level_code?: string | null;
      course_section?: string | null;
      published?: boolean;
      published_by?: string | null;
      published_at?: string | null;
      archived?: boolean;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      title?: Json;
      level_code?: string | null;
      course_section?: string | null;
      published?: boolean;
      published_by?: string | null;
      published_at?: string | null;
      archived?: boolean;
      created_at?: string;
        };
        Relationships: [];
      };
      curriculum_versions: {
        Row: {
      id: string;
      school_id: string;
      curriculum_id: string;
      version: number;
      payload: Json;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      curriculum_id: string;
      version?: number;
      payload?: Json;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      curriculum_id?: string;
      version?: number;
      payload?: Json;
      created_at?: string;
        };
        Relationships: [];
      };
      curriculum_weeks: {
        Row: {
      id: string;
      school_id: string;
      curriculum_id: string;
      phase_id: string | null;
      title: Json;
      no: number | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      curriculum_id: string;
      phase_id?: string | null;
      title?: Json;
      no?: number | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      curriculum_id?: string;
      phase_id?: string | null;
      title?: Json;
      no?: number | null;
        };
        Relationships: [];
      };
      enrolments: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string;
      class_id: string;
      enrolled_at: string;
      status: string;
      created_by: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id: string;
      class_id: string;
      enrolled_at?: string;
      status?: string;
      created_by?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string;
      class_id?: string;
      enrolled_at?: string;
      status?: string;
      created_by?: string | null;
        };
        Relationships: [];
      };
      grants: {
        Row: {
      id: string;
      school_id: string;
      user_id: string;
      action: string;
      granted_by: string | null;
      status: Enums["grant_status"];
      expires_at: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      user_id: string;
      action: string;
      granted_by?: string | null;
      status?: Enums["grant_status"];
      expires_at?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      user_id?: string;
      action?: string;
      granted_by?: string | null;
      status?: Enums["grant_status"];
      expires_at?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      homework: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      date: string;
      class_id: string;
      student_id: string;
      lesson_no: number | null;
      title: string | null;
      status: Enums["homework_status"];
      score: string | null;
      note: string | null;
      recorded_by: string | null;
      due_date: string | null;
      feedback: string | null;
      graded_by: string | null;
      graded_at: string | null;
      batch_id: string | null;
      media_url: string | null;
      media_name: string | null;
      media_id: string | null;
      media_type: string | null;
      page_url: string | null;
      page_id: string | null;
      attachment: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      date: string;
      class_id: string;
      student_id: string;
      lesson_no?: number | null;
      title?: string | null;
      status?: Enums["homework_status"];
      score?: string | null;
      note?: string | null;
      recorded_by?: string | null;
      due_date?: string | null;
      feedback?: string | null;
      graded_by?: string | null;
      graded_at?: string | null;
      batch_id?: string | null;
      media_url?: string | null;
      media_name?: string | null;
      media_id?: string | null;
      media_type?: string | null;
      page_url?: string | null;
      page_id?: string | null;
      attachment?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      date?: string;
      class_id?: string;
      student_id?: string;
      lesson_no?: number | null;
      title?: string | null;
      status?: Enums["homework_status"];
      score?: string | null;
      note?: string | null;
      recorded_by?: string | null;
      due_date?: string | null;
      feedback?: string | null;
      graded_by?: string | null;
      graded_at?: string | null;
      batch_id?: string | null;
      media_url?: string | null;
      media_name?: string | null;
      media_id?: string | null;
      media_type?: string | null;
      page_url?: string | null;
      page_id?: string | null;
      attachment?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      homework_submissions: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      homework_id: string;
      submitted_by: string | null;
      submitted_at: string;
      file_path: string | null;
      note: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      homework_id: string;
      submitted_by?: string | null;
      submitted_at?: string;
      file_path?: string | null;
      note?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      homework_id?: string;
      submitted_by?: string | null;
      submitted_at?: string;
      file_path?: string | null;
      note?: string | null;
        };
        Relationships: [];
      };
      id_mapping: {
        Row: {
      legacy_table: string;
      legacy_id: string;
      new_id: string;
      migrated_at: string;
        };
        Insert: {
      legacy_table: string;
      legacy_id: string;
      new_id: string;
      migrated_at?: string;
        };
        Update: {
      legacy_table?: string;
      legacy_id?: string;
      new_id?: string;
      migrated_at?: string;
        };
        Relationships: [];
      };
      learner_pathways: {
        Row: {
      id: string;
      school_id: string;
      learner_type: Enums["learner_type"];
      programme_id: string | null;
      path: Json;
        };
        Insert: {
      id?: string;
      school_id: string;
      learner_type: Enums["learner_type"];
      programme_id?: string | null;
      path?: Json;
        };
        Update: {
      id?: string;
      school_id?: string;
      learner_type?: Enums["learner_type"];
      programme_id?: string | null;
      path?: Json;
        };
        Relationships: [];
      };
      learning_evidence: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string;
      target_id: string;
      topic_id: string | null;
      lesson_id: string | null;
      source: Enums["evidence_source"];
      quality: Enums["evidence_quality"] | null;
      score: number | null;
      rating: string | null;
      weight: number | null;
      note: string | null;
      context: Json;
      recorded_by: string | null;
      recorded_at: string;
      invalidated: boolean;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id: string;
      target_id: string;
      topic_id?: string | null;
      lesson_id?: string | null;
      source?: Enums["evidence_source"];
      quality?: Enums["evidence_quality"] | null;
      score?: number | null;
      rating?: string | null;
      weight?: number | null;
      note?: string | null;
      context?: Json;
      recorded_by?: string | null;
      recorded_at?: string;
      invalidated?: boolean;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string;
      target_id?: string;
      topic_id?: string | null;
      lesson_id?: string | null;
      source?: Enums["evidence_source"];
      quality?: Enums["evidence_quality"] | null;
      score?: number | null;
      rating?: string | null;
      weight?: number | null;
      note?: string | null;
      context?: Json;
      recorded_by?: string | null;
      recorded_at?: string;
      invalidated?: boolean;
        };
        Relationships: [];
      };
      learning_targets: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      level_code: string | null;
      title: Json;
      active: boolean;
      verification_status: Enums["mapping_status"];
      verified_by: string | null;
      verified_at: string | null;
      created_by: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      level_code?: string | null;
      title?: Json;
      active?: boolean;
      verification_status?: Enums["mapping_status"];
      verified_by?: string | null;
      verified_at?: string | null;
      created_by?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      level_code?: string | null;
      title?: Json;
      active?: boolean;
      verification_status?: Enums["mapping_status"];
      verified_by?: string | null;
      verified_at?: string | null;
      created_by?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      lesson_changes: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      class_id: string;
      from_date: string | null;
      to_date: string | null;
      reason: string | null;
      requested_by: string | null;
      decided_by: string | null;
      decision: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      class_id: string;
      from_date?: string | null;
      to_date?: string | null;
      reason?: string | null;
      requested_by?: string | null;
      decided_by?: string | null;
      decision?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      class_id?: string;
      from_date?: string | null;
      to_date?: string | null;
      reason?: string | null;
      requested_by?: string | null;
      decided_by?: string | null;
      decision?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      lesson_controls: {
        Row: {
      id: string;
      school_id: string;
      class_id: string;
      key: string;
      value: Json;
      updated_by: string | null;
      updated_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      class_id: string;
      key: string;
      value?: Json;
      updated_by?: string | null;
      updated_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      class_id?: string;
      key?: string;
      value?: Json;
      updated_by?: string | null;
      updated_at?: string;
        };
        Relationships: [];
      };
      lesson_logs: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      date: string;
      class_id: string;
      lesson_no: number | null;
      topic: string | null;
      topic_ids: Json;
      participation: string | null;
      teacher_note: string | null;
      duration_min: number | null;
      learning_progress: Json;
      curriculum_version: string | null;
      recommendation_id: string | null;
      created_by: string;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      date: string;
      class_id: string;
      lesson_no?: number | null;
      topic?: string | null;
      topic_ids?: Json;
      participation?: string | null;
      teacher_note?: string | null;
      duration_min?: number | null;
      learning_progress?: Json;
      curriculum_version?: string | null;
      recommendation_id?: string | null;
      created_by: string;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      date?: string;
      class_id?: string;
      lesson_no?: number | null;
      topic?: string | null;
      topic_ids?: Json;
      participation?: string | null;
      teacher_note?: string | null;
      duration_min?: number | null;
      learning_progress?: Json;
      curriculum_version?: string | null;
      recommendation_id?: string | null;
      created_by?: string;
      created_at?: string;
        };
        Relationships: [];
      };
      lesson_material_recommendations: {
        Row: {
      id: string;
      school_id: string;
      lesson_id: string;
      material_id: string;
      score: number | null;
      status: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      lesson_id: string;
      material_id: string;
      score?: number | null;
      status?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      lesson_id?: string;
      material_id?: string;
      score?: number | null;
      status?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      lesson_plan_imports: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      teacher_id: string | null;
      source_text: string | null;
      parsed: Json | null;
      status: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      teacher_id?: string | null;
      source_text?: string | null;
      parsed?: Json | null;
      status?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      teacher_id?: string | null;
      source_text?: string | null;
      parsed?: Json | null;
      status?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      lesson_plans: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      teacher_id: string;
      class_id: string | null;
      lesson_id: string | null;
      plan: Json;
      source: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      teacher_id: string;
      class_id?: string | null;
      lesson_id?: string | null;
      plan?: Json;
      source?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      teacher_id?: string;
      class_id?: string | null;
      lesson_id?: string | null;
      plan?: Json;
      source?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      lesson_ratings: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      lesson_log_id: string | null;
      student_id: string | null;
      rating: Enums["rating_value"];
      created_by: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      lesson_log_id?: string | null;
      student_id?: string | null;
      rating: Enums["rating_value"];
      created_by?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      lesson_log_id?: string | null;
      student_id?: string | null;
      rating?: Enums["rating_value"];
      created_by?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      lesson_transactions: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      lesson_log_id: string | null;
      state: string | null;
      started_at: string | null;
      finished_at: string | null;
      error: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      lesson_log_id?: string | null;
      state?: string | null;
      started_at?: string | null;
      finished_at?: string | null;
      error?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      lesson_log_id?: string | null;
      state?: string | null;
      started_at?: string | null;
      finished_at?: string | null;
      error?: string | null;
        };
        Relationships: [];
      };
      lessons: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      stable_id: string;
      unit_id: string;
      code: string | null;
      no: number | null;
      title: Json;
      objectives_meta: Json;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      stable_id: string;
      unit_id: string;
      code?: string | null;
      no?: number | null;
      title?: Json;
      objectives_meta?: Json;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      stable_id?: string;
      unit_id?: string;
      code?: string | null;
      no?: number | null;
      title?: Json;
      objectives_meta?: Json;
      created_at?: string;
        };
        Relationships: [];
      };
      level_history: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string;
      level_code: string | null;
      started_at: string | null;
      completed_at: string | null;
      final_progress: number | null;
      badges_earned: number | null;
      final_assessment: string | null;
      status: string | null;
      legacy: boolean;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id: string;
      level_code?: string | null;
      started_at?: string | null;
      completed_at?: string | null;
      final_progress?: number | null;
      badges_earned?: number | null;
      final_assessment?: string | null;
      status?: string | null;
      legacy?: boolean;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string;
      level_code?: string | null;
      started_at?: string | null;
      completed_at?: string | null;
      final_progress?: number | null;
      badges_earned?: number | null;
      final_assessment?: string | null;
      status?: string | null;
      legacy?: boolean;
        };
        Relationships: [];
      };
      level_objectives: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      level_code: string | null;
      objective_text: Json;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      level_code?: string | null;
      objective_text?: Json;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      level_code?: string | null;
      objective_text?: Json;
      created_at?: string;
        };
        Relationships: [];
      };
      level_requirements: {
        Row: {
      id: string;
      school_id: string;
      level_code: string | null;
      requirement: Json;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      level_code?: string | null;
      requirement?: Json;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      level_code?: string | null;
      requirement?: Json;
      created_at?: string;
        };
        Relationships: [];
      };
      levels: {
        Row: {
      id: string;
      school_id: string;
      code: string;
      cefr: string | null;
      label: Json;
      sort: number;
        };
        Insert: {
      id?: string;
      school_id: string;
      code: string;
      cefr?: string | null;
      label?: Json;
      sort?: number;
        };
        Update: {
      id?: string;
      school_id?: string;
      code?: string;
      cefr?: string | null;
      label?: Json;
      sort?: number;
        };
        Relationships: [];
      };
      material_assignments: {
        Row: {
      id: string;
      school_id: string;
      material_id: string;
      scope_type: string;
      scope_id: string;
      is_primary: boolean;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      material_id: string;
      scope_type: string;
      scope_id: string;
      is_primary?: boolean;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      material_id?: string;
      scope_type?: string;
      scope_id?: string;
      is_primary?: boolean;
      created_at?: string;
        };
        Relationships: [];
      };
      material_feedback: {
        Row: {
      id: string;
      school_id: string;
      material_id: string;
      rater_id: string | null;
      rating: Enums["rating_value"] | null;
      note: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      material_id: string;
      rater_id?: string | null;
      rating?: Enums["rating_value"] | null;
      note?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      material_id?: string;
      rater_id?: string | null;
      rating?: Enums["rating_value"] | null;
      note?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      material_lessons: {
        Row: {
      id: string;
      school_id: string;
      material_id: string;
      lesson_id: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      material_id: string;
      lesson_id: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      material_id?: string;
      lesson_id?: string;
        };
        Relationships: [];
      };
      material_mappings: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      material_unit_id: string;
      target_id: string;
      scope: string | null;
      page_start: number | null;
      page_end: number | null;
      purpose: string | null;
      status: Enums["mapping_status"];
      proposed_by: string | null;
      decided_by: string | null;
      decided_at: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      material_unit_id: string;
      target_id: string;
      scope?: string | null;
      page_start?: number | null;
      page_end?: number | null;
      purpose?: string | null;
      status?: Enums["mapping_status"];
      proposed_by?: string | null;
      decided_by?: string | null;
      decided_at?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      material_unit_id?: string;
      target_id?: string;
      scope?: string | null;
      page_start?: number | null;
      page_end?: number | null;
      purpose?: string | null;
      status?: Enums["mapping_status"];
      proposed_by?: string | null;
      decided_by?: string | null;
      decided_at?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      material_units: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      material_id: string;
      no: number | null;
      title: Json;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      material_id: string;
      no?: number | null;
      title?: Json;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      material_id?: string;
      no?: number | null;
      title?: Json;
        };
        Relationships: [];
      };
      material_usage: {
        Row: {
      id: string;
      school_id: string;
      material_id: string;
      used_by: string | null;
      used_at: string;
      context: Json;
        };
        Insert: {
      id?: string;
      school_id: string;
      material_id: string;
      used_by?: string | null;
      used_at?: string;
      context?: Json;
        };
        Update: {
      id?: string;
      school_id?: string;
      material_id?: string;
      used_by?: string | null;
      used_at?: string;
      context?: Json;
        };
        Relationships: [];
      };
      materials: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      title: Json;
      type: Enums["material_type"];
      level_code: string | null;
      publisher: string | null;
      isbn: string | null;
      drive_url: string | null;
      created_by: string | null;
      created_at: string;
      updated_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      title?: Json;
      type?: Enums["material_type"];
      level_code?: string | null;
      publisher?: string | null;
      isbn?: string | null;
      drive_url?: string | null;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      title?: Json;
      type?: Enums["material_type"];
      level_code?: string | null;
      publisher?: string | null;
      isbn?: string | null;
      drive_url?: string | null;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
        };
        Relationships: [];
      };
      message_participants: {
        Row: {
      thread_id: string;
      user_id: string;
      read_at: string | null;
        };
        Insert: {
      thread_id: string;
      user_id: string;
      read_at?: string | null;
        };
        Update: {
      thread_id?: string;
      user_id?: string;
      read_at?: string | null;
        };
        Relationships: [];
      };
      message_threads: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      subject: string | null;
      created_by: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      subject?: string | null;
      created_by?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      subject?: string | null;
      created_by?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      messages: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      thread_id: string | null;
      from_id: string | null;
      body: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      thread_id?: string | null;
      from_id?: string | null;
      body?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      thread_id?: string | null;
      from_id?: string | null;
      body?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      methodology: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      title: Json;
      body: Json;
      level_code: string | null;
      created_by: string | null;
      updated_by: string | null;
      created_at: string;
      updated_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      title?: Json;
      body?: Json;
      level_code?: string | null;
      created_by?: string | null;
      updated_by?: string | null;
      created_at?: string;
      updated_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      title?: Json;
      body?: Json;
      level_code?: string | null;
      created_by?: string | null;
      updated_by?: string | null;
      created_at?: string;
      updated_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      user_id: string;
      kind: string | null;
      payload: Json;
      read_at: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      user_id: string;
      kind?: string | null;
      payload?: Json;
      read_at?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      user_id?: string;
      kind?: string | null;
      payload?: Json;
      read_at?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      objective_targets: {
        Row: {
      id: string;
      school_id: string;
      objective_id: string;
      target_id: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      objective_id: string;
      target_id: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      objective_id?: string;
      target_id?: string;
        };
        Relationships: [];
      };
      objectives: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      stable_id: string;
      lesson_id: string;
      code: string | null;
      text: Json;
      cefr: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      stable_id: string;
      lesson_id: string;
      code?: string | null;
      text?: Json;
      cefr?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      stable_id?: string;
      lesson_id?: string;
      code?: string | null;
      text?: Json;
      cefr?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      parents: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      user_id: string | null;
      name: string;
      phone: string | null;
      email: string | null;
      notes: string | null;
      created_by: string | null;
      created_at: string;
      updated_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      user_id?: string | null;
      name: string;
      phone?: string | null;
      email?: string | null;
      notes?: string | null;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      user_id?: string | null;
      name?: string;
      phone?: string | null;
      email?: string | null;
      notes?: string | null;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
        };
        Relationships: [];
      };
      payment_ledger: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string;
      class_id: string | null;
      lesson_key: string | null;
      amount: number;
      currency: string;
      kind: string | null;
      status: Enums["payment_status"];
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id: string;
      class_id?: string | null;
      lesson_key?: string | null;
      amount?: number;
      currency?: string;
      kind?: string | null;
      status?: Enums["payment_status"];
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string;
      class_id?: string | null;
      lesson_key?: string | null;
      amount?: number;
      currency?: string;
      kind?: string | null;
      status?: Enums["payment_status"];
      created_at?: string;
        };
        Relationships: [];
      };
      payment_proofs: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      payment_id: string;
      file_path: string | null;
      submitted_by: string | null;
      submitted_at: string;
      status: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      payment_id: string;
      file_path?: string | null;
      submitted_by?: string | null;
      submitted_at?: string;
      status?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      payment_id?: string;
      file_path?: string | null;
      submitted_by?: string | null;
      submitted_at?: string;
      status?: string | null;
        };
        Relationships: [];
      };
      payments: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string;
      amount: number;
      currency: string;
      pay_type: string | null;
      status: Enums["payment_status"];
      due_date: string | null;
      confirmed_at: string | null;
      created_by: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id: string;
      amount: number;
      currency?: string;
      pay_type?: string | null;
      status?: Enums["payment_status"];
      due_date?: string | null;
      confirmed_at?: string | null;
      created_by?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string;
      amount?: number;
      currency?: string;
      pay_type?: string | null;
      status?: Enums["payment_status"];
      due_date?: string | null;
      confirmed_at?: string | null;
      created_by?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      permission_actions: {
        Row: {
      action: string;
      category: string;
      builtin: boolean;
        };
        Insert: {
      action: string;
      category?: string;
      builtin?: boolean;
        };
        Update: {
      action?: string;
      category?: string;
      builtin?: boolean;
        };
        Relationships: [];
      };
      practice_attempts: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string;
      class_id: string | null;
      lesson_date: string | null;
      topic: string | null;
      attempt_no: number;
      total: number | null;
      correct: number | null;
      pct: number | null;
      passed: boolean | null;
      points: number | null;
      assessment_id: string | null;
      source: string | null;
      started_at: string | null;
      finished_at: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id: string;
      class_id?: string | null;
      lesson_date?: string | null;
      topic?: string | null;
      attempt_no?: number;
      total?: number | null;
      correct?: number | null;
      pct?: number | null;
      passed?: boolean | null;
      points?: number | null;
      assessment_id?: string | null;
      source?: string | null;
      started_at?: string | null;
      finished_at?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string;
      class_id?: string | null;
      lesson_date?: string | null;
      topic?: string | null;
      attempt_no?: number;
      total?: number | null;
      correct?: number | null;
      pct?: number | null;
      passed?: boolean | null;
      points?: number | null;
      assessment_id?: string | null;
      source?: string | null;
      started_at?: string | null;
      finished_at?: string | null;
        };
        Relationships: [];
      };
      pricing: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      name: Json;
      level_code: string | null;
      price: number;
      currency: string;
      active: boolean;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      name?: Json;
      level_code?: string | null;
      price?: number;
      currency?: string;
      active?: boolean;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      name?: Json;
      level_code?: string | null;
      price?: number;
      currency?: string;
      active?: boolean;
      created_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      email: string | null;
      name: string | null;
      role_id: string | null;
      role_base: Enums["role_base"];
      phone: string | null;
      avatar_path: string | null;
      locale: Enums["app_locale"];
      notify_lang: Enums["app_locale"];
      notify_prompt_month: string | null;
      wallet_type: string | null;
      wallet_active: boolean;
      monthly_salary: number | null;
      currency: string | null;
      username: string | null;
      pay_types: Json;
      subjects: Json;
      status: Enums["user_status"];
      must_change_password: boolean;
      last_login: string | null;
      linked_ids: Json;
      requested_role: string | null;
      approved_by: string | null;
      approved_at: string | null;
      signup_note: string | null;
      country: string | null;
      city: string | null;
      email_opt_out: boolean;
      appeal_status: string | null;
      appeal_note: string | null;
      appeal_at: string | null;
      appeal_decided_by: string | null;
      appeal_decided_at: string | null;
      appeal_count: number;
      appeal_final: boolean;
      dob: string | null;
      recovery_question: string | null;
      recovery_answer_hash: string | null;
      recovery_answer_salt: string | null;
      recovery_status: string | null;
      created_at: string;
      updated_at: string;
        };
        Insert: {
      id: string;
      school_id: string;
      legacy_id?: string | null;
      email?: string | null;
      name?: string | null;
      role_id?: string | null;
      role_base?: Enums["role_base"];
      phone?: string | null;
      avatar_path?: string | null;
      locale?: Enums["app_locale"];
      notify_lang?: Enums["app_locale"];
      notify_prompt_month?: string | null;
      wallet_type?: string | null;
      wallet_active?: boolean;
      monthly_salary?: number | null;
      currency?: string | null;
      username?: string | null;
      pay_types?: Json;
      subjects?: Json;
      status?: Enums["user_status"];
      must_change_password?: boolean;
      last_login?: string | null;
      linked_ids?: Json;
      requested_role?: string | null;
      approved_by?: string | null;
      approved_at?: string | null;
      signup_note?: string | null;
      country?: string | null;
      city?: string | null;
      email_opt_out?: boolean;
      appeal_status?: string | null;
      appeal_note?: string | null;
      appeal_at?: string | null;
      appeal_decided_by?: string | null;
      appeal_decided_at?: string | null;
      appeal_count?: number;
      appeal_final?: boolean;
      dob?: string | null;
      recovery_question?: string | null;
      recovery_answer_hash?: string | null;
      recovery_answer_salt?: string | null;
      recovery_status?: string | null;
      created_at?: string;
      updated_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      email?: string | null;
      name?: string | null;
      role_id?: string | null;
      role_base?: Enums["role_base"];
      phone?: string | null;
      avatar_path?: string | null;
      locale?: Enums["app_locale"];
      notify_lang?: Enums["app_locale"];
      notify_prompt_month?: string | null;
      wallet_type?: string | null;
      wallet_active?: boolean;
      monthly_salary?: number | null;
      currency?: string | null;
      username?: string | null;
      pay_types?: Json;
      subjects?: Json;
      status?: Enums["user_status"];
      must_change_password?: boolean;
      last_login?: string | null;
      linked_ids?: Json;
      requested_role?: string | null;
      approved_by?: string | null;
      approved_at?: string | null;
      signup_note?: string | null;
      country?: string | null;
      city?: string | null;
      email_opt_out?: boolean;
      appeal_status?: string | null;
      appeal_note?: string | null;
      appeal_at?: string | null;
      appeal_decided_by?: string | null;
      appeal_decided_at?: string | null;
      appeal_count?: number;
      appeal_final?: boolean;
      dob?: string | null;
      recovery_question?: string | null;
      recovery_answer_hash?: string | null;
      recovery_answer_salt?: string | null;
      recovery_status?: string | null;
      created_at?: string;
      updated_at?: string;
        };
        Relationships: [];
      };
      programmes: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      stable_id: string;
      code: string | null;
      name: Json;
      type: string | null;
      standard: boolean;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      stable_id: string;
      code?: string | null;
      name?: Json;
      type?: string | null;
      standard?: boolean;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      stable_id?: string;
      code?: string | null;
      name?: Json;
      type?: string | null;
      standard?: boolean;
      created_at?: string;
        };
        Relationships: [];
      };
      progress_cache: {
        Row: {
      id: string;
      school_id: string;
      student_id: string;
      snapshot: Json;
      snapshot_level: string | null;
      snapshot_updated_at: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      student_id: string;
      snapshot?: Json;
      snapshot_level?: string | null;
      snapshot_updated_at?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      student_id?: string;
      snapshot?: Json;
      snapshot_level?: string | null;
      snapshot_updated_at?: string | null;
        };
        Relationships: [];
      };
      progression_audit: {
        Row: {
      id: string;
      school_id: string;
      student_id: string | null;
      change: Json;
      actor_id: string | null;
      at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      student_id?: string | null;
      change?: Json;
      actor_id?: string | null;
      at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      student_id?: string | null;
      change?: Json;
      actor_id?: string | null;
      at?: string;
        };
        Relationships: [];
      };
      recommendation_history: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string | null;
      kind: string | null;
      payload: Json;
      feedback: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id?: string | null;
      kind?: string | null;
      payload?: Json;
      feedback?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string | null;
      kind?: string | null;
      payload?: Json;
      feedback?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      remarks: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string | null;
      subject: string | null;
      body: string | null;
      recorded_by: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id?: string | null;
      subject?: string | null;
      body?: string | null;
      recorded_by?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string | null;
      subject?: string | null;
      body?: string | null;
      recorded_by?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      reminders: {
        Row: {
      id: string;
      school_id: string;
      kind: string;
      ref_id: string | null;
      user_id: string | null;
      sent_at: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      kind: string;
      ref_id?: string | null;
      user_id?: string | null;
      sent_at?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      kind?: string;
      ref_id?: string | null;
      user_id?: string | null;
      sent_at?: string | null;
        };
        Relationships: [];
      };
      resources: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      title: Json;
      url: string | null;
      file_path: string | null;
      kind: string | null;
      created_by: string | null;
      created_at: string;
      deleted_at: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      title?: Json;
      url?: string | null;
      file_path?: string | null;
      kind?: string | null;
      created_by?: string | null;
      created_at?: string;
      deleted_at?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      title?: Json;
      url?: string | null;
      file_path?: string | null;
      kind?: string | null;
      created_by?: string | null;
      created_at?: string;
      deleted_at?: string | null;
        };
        Relationships: [];
      };
      role_action_matrix: {
        Row: {
      role_key: string;
      action: string;
        };
        Insert: {
      role_key: string;
      action: string;
        };
        Update: {
      role_key?: string;
      action?: string;
        };
        Relationships: [];
      };
      roles: {
        Row: {
      id: string;
      school_id: string;
      key: string;
      label: string;
      rank: number;
      base_role: Enums["role_base"];
      permissions: string[];
      needs_approval: boolean;
      builtin: boolean;
      edited: boolean;
      created_by: string | null;
      created_at: string;
      updated_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      key: string;
      label: string;
      rank?: number;
      base_role?: Enums["role_base"];
      permissions?: string[];
      needs_approval?: boolean;
      builtin?: boolean;
      edited?: boolean;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      key?: string;
      label?: string;
      rank?: number;
      base_role?: Enums["role_base"];
      permissions?: string[];
      needs_approval?: boolean;
      builtin?: boolean;
      edited?: boolean;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
        };
        Relationships: [];
      };
      salaries: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      user_id: string;
      month: string;
      amount: number;
      currency: string;
      status: Enums["salary_status"];
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      user_id: string;
      month: string;
      amount?: number;
      currency?: string;
      status?: Enums["salary_status"];
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      user_id?: string;
      month?: string;
      amount?: number;
      currency?: string;
      status?: Enums["salary_status"];
      created_at?: string;
        };
        Relationships: [];
      };
      schools: {
        Row: {
      id: string;
      name: string;
      timezone: string;
      currency: string;
      locale: Enums["app_locale"];
      branding: Json;
      created_at: string;
        };
        Insert: {
      id?: string;
      name: string;
      timezone?: string;
      currency?: string;
      locale?: Enums["app_locale"];
      branding?: Json;
      created_at?: string;
        };
        Update: {
      id?: string;
      name?: string;
      timezone?: string;
      currency?: string;
      locale?: Enums["app_locale"];
      branding?: Json;
      created_at?: string;
        };
        Relationships: [];
      };
      settings: {
        Row: {
      id: string;
      school_id: string;
      key: string;
      value: Json;
      updated_by: string | null;
      updated_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      key: string;
      value?: Json;
      updated_by?: string | null;
      updated_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      key?: string;
      value?: Json;
      updated_by?: string | null;
      updated_at?: string;
        };
        Relationships: [];
      };
      skills: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      code: string | null;
      label: Json;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      code?: string | null;
      label?: Json;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      code?: string | null;
      label?: Json;
      created_at?: string;
        };
        Relationships: [];
      };
      special_course_topics: {
        Row: {
      special_course_id: string;
      topic_id: string;
      position: number;
        };
        Insert: {
      special_course_id: string;
      topic_id: string;
      position?: number;
        };
        Update: {
      special_course_id?: string;
      topic_id?: string;
      position?: number;
        };
        Relationships: [];
      };
      special_courses: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      name: Json;
      level_code: string | null;
      programme_id: string | null;
      active: boolean;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      name?: Json;
      level_code?: string | null;
      programme_id?: string | null;
      active?: boolean;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      name?: Json;
      level_code?: string | null;
      programme_id?: string | null;
      active?: boolean;
      created_at?: string;
        };
        Relationships: [];
      };
      spotlight: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      month: string;
      picks: Json;
      status: Enums["spotlight_status"];
      published_by: string | null;
      published_at: string | null;
      locked_at: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      month: string;
      picks?: Json;
      status?: Enums["spotlight_status"];
      published_by?: string | null;
      published_at?: string | null;
      locked_at?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      month?: string;
      picks?: Json;
      status?: Enums["spotlight_status"];
      published_by?: string | null;
      published_at?: string | null;
      locked_at?: string | null;
        };
        Relationships: [];
      };
      student_badges: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string;
      badge_id: string;
      awarded_by: string | null;
      awarded_at: string;
      public: boolean;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id: string;
      badge_id: string;
      awarded_by?: string | null;
      awarded_at?: string;
      public?: boolean;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string;
      badge_id?: string;
      awarded_by?: string | null;
      awarded_at?: string;
      public?: boolean;
        };
        Relationships: [];
      };
      student_parents: {
        Row: {
      student_id: string;
      parent_id: string;
      relationship: string | null;
      created_at: string;
        };
        Insert: {
      student_id: string;
      parent_id: string;
      relationship?: string | null;
      created_at?: string;
        };
        Update: {
      student_id?: string;
      parent_id?: string;
      relationship?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      students: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_no: string | null;
      user_id: string | null;
      name: string;
      level_code: string | null;
      gender: Enums["gender"] | null;
      dob: string | null;
      phone: string | null;
      email: string | null;
      address: string | null;
      status: Enums["user_status"];
      avatar_path: string | null;
      photo_path: string | null;
      joined_at: string | null;
      notes: string | null;
      learner_type: Enums["learner_type"] | null;
      primary_material_id: string | null;
      special_course_id: string | null;
      current_progress: number | null;
      progress_mode: string | null;
      academic_status: string | null;
      created_by: string | null;
      created_at: string;
      updated_at: string;
      deleted_at: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_no?: string | null;
      user_id?: string | null;
      name: string;
      level_code?: string | null;
      gender?: Enums["gender"] | null;
      dob?: string | null;
      phone?: string | null;
      email?: string | null;
      address?: string | null;
      status?: Enums["user_status"];
      avatar_path?: string | null;
      photo_path?: string | null;
      joined_at?: string | null;
      notes?: string | null;
      learner_type?: Enums["learner_type"] | null;
      primary_material_id?: string | null;
      special_course_id?: string | null;
      current_progress?: number | null;
      progress_mode?: string | null;
      academic_status?: string | null;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
      deleted_at?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_no?: string | null;
      user_id?: string | null;
      name?: string;
      level_code?: string | null;
      gender?: Enums["gender"] | null;
      dob?: string | null;
      phone?: string | null;
      email?: string | null;
      address?: string | null;
      status?: Enums["user_status"];
      avatar_path?: string | null;
      photo_path?: string | null;
      joined_at?: string | null;
      notes?: string | null;
      learner_type?: Enums["learner_type"] | null;
      primary_material_id?: string | null;
      special_course_id?: string | null;
      current_progress?: number | null;
      progress_mode?: string | null;
      academic_status?: string | null;
      created_by?: string | null;
      created_at?: string;
      updated_at?: string;
      deleted_at?: string | null;
        };
        Relationships: [];
      };
      subjects: {
        Row: {
      id: string;
      school_id: string;
      name: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      name: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      name?: string;
        };
        Relationships: [];
      };
      teacher_bios: {
        Row: {
      user_id: string;
      school_id: string;
      legacy_id: string | null;
      position: string | null;
      headline: string | null;
      bio: string | null;
      experience: string | null;
      education: string | null;
      qualifications: Json;
      specialisms: Json;
      languages: Json;
      age_groups: Json;
      levels: Json;
      approach: string | null;
      achievements: string | null;
      interests: string | null;
      availability: string | null;
      favoured: boolean;
      updated_by: string | null;
      updated_at: string;
        };
        Insert: {
      user_id: string;
      school_id: string;
      legacy_id?: string | null;
      position?: string | null;
      headline?: string | null;
      bio?: string | null;
      experience?: string | null;
      education?: string | null;
      qualifications?: Json;
      specialisms?: Json;
      languages?: Json;
      age_groups?: Json;
      levels?: Json;
      approach?: string | null;
      achievements?: string | null;
      interests?: string | null;
      availability?: string | null;
      favoured?: boolean;
      updated_by?: string | null;
      updated_at?: string;
        };
        Update: {
      user_id?: string;
      school_id?: string;
      legacy_id?: string | null;
      position?: string | null;
      headline?: string | null;
      bio?: string | null;
      experience?: string | null;
      education?: string | null;
      qualifications?: Json;
      specialisms?: Json;
      languages?: Json;
      age_groups?: Json;
      levels?: Json;
      approach?: string | null;
      achievements?: string | null;
      interests?: string | null;
      availability?: string | null;
      favoured?: boolean;
      updated_by?: string | null;
      updated_at?: string;
        };
        Relationships: [];
      };
      teacher_materials: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      teacher_id: string;
      title: Json;
      kind: string | null;
      payload: Json;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      teacher_id: string;
      title?: Json;
      kind?: string | null;
      payload?: Json;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      teacher_id?: string;
      title?: Json;
      kind?: string | null;
      payload?: Json;
      created_at?: string;
        };
        Relationships: [];
      };
      teacher_rating_audit: {
        Row: {
      id: string;
      school_id: string;
      teacher_id: string | null;
      actor_id: string | null;
      change: Json;
      at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      teacher_id?: string | null;
      actor_id?: string | null;
      change?: Json;
      at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      teacher_id?: string | null;
      actor_id?: string | null;
      change?: Json;
      at?: string;
        };
        Relationships: [];
      };
      teacher_ratings: {
        Row: {
      id: string;
      school_id: string;
      teacher_id: string;
      rater_id: string | null;
      role: string | null;
      rating: Enums["rating_value"];
      comment: string | null;
      moderated: boolean;
      moderated_by: string | null;
      moderated_at: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      teacher_id: string;
      rater_id?: string | null;
      role?: string | null;
      rating: Enums["rating_value"];
      comment?: string | null;
      moderated?: boolean;
      moderated_by?: string | null;
      moderated_at?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      teacher_id?: string;
      rater_id?: string | null;
      role?: string | null;
      rating?: Enums["rating_value"];
      comment?: string | null;
      moderated?: boolean;
      moderated_by?: string | null;
      moderated_at?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
      terms: {
        Row: {
      id: string;
      school_id: string;
      academic_year_id: string;
      name: string;
      starts_on: string | null;
      ends_on: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      academic_year_id: string;
      name: string;
      starts_on?: string | null;
      ends_on?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      academic_year_id?: string;
      name?: string;
      starts_on?: string | null;
      ends_on?: string | null;
        };
        Relationships: [];
      };
      topic_progress: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      student_id: string;
      topic_id: string;
      progress: number | null;
      status: Enums["progress_status"];
      evidence_count: number;
      updated_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      student_id: string;
      topic_id: string;
      progress?: number | null;
      status?: Enums["progress_status"];
      evidence_count?: number;
      updated_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      student_id?: string;
      topic_id?: string;
      progress?: number | null;
      status?: Enums["progress_status"];
      evidence_count?: number;
      updated_at?: string;
        };
        Relationships: [];
      };
      topic_skills: {
        Row: {
      topic_id: string;
      skill_id: string;
      weight: number | null;
        };
        Insert: {
      topic_id: string;
      skill_id: string;
      weight?: number | null;
        };
        Update: {
      topic_id?: string;
      skill_id?: string;
      weight?: number | null;
        };
        Relationships: [];
      };
      topic_targets: {
        Row: {
      topic_id: string;
      target_id: string;
      required: boolean;
        };
        Insert: {
      topic_id: string;
      target_id: string;
      required?: boolean;
        };
        Update: {
      topic_id?: string;
      target_id?: string;
      required?: boolean;
        };
        Relationships: [];
      };
      units: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      stable_id: string;
      programme_id: string;
      code: string | null;
      no: number | null;
      title: Json;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      stable_id: string;
      programme_id: string;
      code?: string | null;
      no?: number | null;
      title?: Json;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      stable_id?: string;
      programme_id?: string;
      code?: string | null;
      no?: number | null;
      title?: Json;
      created_at?: string;
        };
        Relationships: [];
      };
      uploads: {
        Row: {
      id: string;
      school_id: string;
      storage_path: string;
      bucket: string;
      mime: string | null;
      size_bytes: number | null;
      original_name: string | null;
      uploaded_by: string | null;
      uploaded_at: string;
      deleted_at: string | null;
        };
        Insert: {
      id?: string;
      school_id: string;
      storage_path: string;
      bucket: string;
      mime?: string | null;
      size_bytes?: number | null;
      original_name?: string | null;
      uploaded_by?: string | null;
      uploaded_at?: string;
      deleted_at?: string | null;
        };
        Update: {
      id?: string;
      school_id?: string;
      storage_path?: string;
      bucket?: string;
      mime?: string | null;
      size_bytes?: number | null;
      original_name?: string | null;
      uploaded_by?: string | null;
      uploaded_at?: string;
      deleted_at?: string | null;
        };
        Relationships: [];
      };
      wallet_ledger: {
        Row: {
      id: string;
      school_id: string;
      legacy_id: string | null;
      user_id: string;
      class_id: string | null;
      month: string;
      lesson_log_id: string | null;
      amount: number;
      currency: string;
      kind: string | null;
      created_at: string;
        };
        Insert: {
      id?: string;
      school_id: string;
      legacy_id?: string | null;
      user_id: string;
      class_id?: string | null;
      month: string;
      lesson_log_id?: string | null;
      amount?: number;
      currency?: string;
      kind?: string | null;
      created_at?: string;
        };
        Update: {
      id?: string;
      school_id?: string;
      legacy_id?: string | null;
      user_id?: string;
      class_id?: string | null;
      month?: string;
      lesson_log_id?: string | null;
      amount?: number;
      currency?: string;
      kind?: string | null;
      created_at?: string;
        };
        Relationships: [];
      };
    };
    Functions: {
      audit_changes: {
        Args: Record<string, never>;
        Returns: Json;
      };
      current_profile: {
        Args: Record<string, never>;
        Returns: Json;
      };
      handle_new_user: {
        Args: Record<string, never>;
        Returns: Json;
      };
      has_perm: {
        Args: { p_action: string };
        Returns: Json;
      };
      has_role: {
        Args: { p_key: string };
        Returns: Json;
      };
      normalize_evidence_weights: {
        Args: { p_student: string; p_target: string };
        Returns: Json;
      };
      prevent_duplicate_payment: {
        Args: Record<string, never>;
        Returns: Json;
      };
      recompute_student_balance: {
        Args: { p_student: string };
        Returns: Json;
      };
      recompute_wallet: {
        Args: { p_user: string; p_month: string };
        Returns: Json;
      };
      resolve_translation: {
        Args: { p_hash: string; p_locale: Enums["app_locale"] };
        Returns: Json;
      };
      set_updated_at: {
        Args: Record<string, never>;
        Returns: Json;
      };
      stable_id: {
        Args: { p_prefix: string; p_code: string; p_no: number };
        Returns: Json;
      };
    };
    Enums: Enums;
    CompositeTypes: Record<string, never>;
  };
  fsms: {
    Functions: {
      assign_user_role: {
        Args: { p_user: string; p_role_key: string };
        Returns: Json;
      };
      can_see_class: {
        Args: { p_class: string };
        Returns: Json;
      };
      can_see_student: {
        Args: { p_student: string };
        Returns: Json;
      };
      current_profile: {
        Args: Record<string, never>;
        Returns: Json;
      };
      current_profile_id: {
        Args: Record<string, never>;
        Returns: Json;
      };
      current_role_base: {
        Args: Record<string, never>;
        Returns: Json;
      };
      current_school_id: {
        Args: Record<string, never>;
        Returns: Json;
      };
      dashboard_summary: {
        Args: Record<string, never>;
        Returns: Json;
      };
      ensure_builtin_roles: {
        Args: { p_school: string };
        Returns: Json;
      };
      has_perm: {
        Args: { p_action: string };
        Returns: Json;
      };
      has_role: {
        Args: { p_key: string };
        Returns: Json;
      };
      is_finance: {
        Args: Record<string, never>;
        Returns: Json;
      };
      is_leadership: {
        Args: Record<string, never>;
        Returns: Json;
      };
      is_money_role: {
        Args: Record<string, never>;
        Returns: Json;
      };
      is_office: {
        Args: Record<string, never>;
        Returns: Json;
      };
      is_staff: {
        Args: Record<string, never>;
        Returns: Json;
      };
      is_superuser: {
        Args: Record<string, never>;
        Returns: Json;
      };
      parent_search: {
        Args: { p_search?: string; p_page_size?: number; p_cursor?: string };
        Returns: Json;
      };
      role_rank: {
        Args: Record<string, never>;
        Returns: Json;
      };
      set_user_status: {
        Args: { p_user: string; p_status: string };
        Returns: Json;
      };
      student_detail: {
        Args: { p_student: string };
        Returns: Json;
      };
      student_search: {
        Args: { p_search?: string; p_level?: string; p_status?: string; p_page_size?: number; p_cursor?: string };
        Returns: Json;
      };
      user_search: {
        Args: { p_search?: string; p_role?: string; p_page_size?: number; p_cursor?: string };
        Returns: Json;
      };
    };
    Enums: Enums;
  };
};
